version: '2'
services:
  mongo:
    image: "mongo:3"
    volumes:
      - /opt/docker/docker_storage/graylog/mongo:/data/db
  
  elasticsearch:
    image: "elasticsearch"
    command: "elasticsearch -Des.cluster.name='graylog'"
    volumes:
      - /opt/docker/docker_storage/graylog/elasticsearch:/usr/share/elasticsearch/data
  
  graylog:
    image: graylog/graylog
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_WEB_ENDPOINT_URI: http://127.0.0.1:9000/api
    volumes:
      - /opt/docker/docker_storage/graylog/graylog/journal:/usr/share/graylog/data/journal
      - ./config:/usr/share/graylog/data/config
    links:
      - mongo
      - elasticsearch
    ports:
      - "9000:9000"
      - "12201:12201/udp"
      - "1514:1514/udp"