version: '2'
services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=passowrd_1989
    volumes:
      - /opt/docker/docker_storage/grafana/grafana:/var/lib/grafana
    links: 
      - influxdb:influx

  influxdb:
    image: influxdb
    ports:
      - 8083:8083
      - 8086:8086
    volumes:
      - /opt/docker/docker_storage/grafana/influxdb:/var/lib/influxdb
